# Generated by Django 5.1.7 on 2025-03-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_session_year_sports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
    ]
