# Generated by Django 5.1.7 on 2025-03-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sport_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sport'),
        ),
    ]
