# Generated by Django 5.1.7 on 2025-03-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_attendance_tournament_id_attendance_sport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sport_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='tournament_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.tournament'),
        ),
    ]
