# Generated by Django 5.1.7 on 2025-03-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_attendance_sport_id_attendance_tournament_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
