# Generated by Django 5.1.7 on 2025-03-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
