# Generated by Django 5.1.7 on 2025-04-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_studentachievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAchievement',
        ),
    ]
